# Generated by Django 6.0.1 on 2026-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'student'), ('Teacher', 'teacher')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
