# Generated by Django 6.0.1 on 2026-01-23 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'student'), ('Teacher', 'teacher')], max_length=50, null=True),
        ),
    ]
