# Generated by Django 6.0.1 on 2026-01-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_users_email_users_avatar_users_birthday_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
