# Generated by Django 6.0.1 on 2026-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='study_year',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
