# Generated by Django 6.0.1 on 2026-01-23 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_grades'),
        ('student', '0002_students_study_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='klass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.klass'),
            preserve_default=False,
        ),
    ]
