# Generated by Django 6.0.1 on 2026-01-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tasktodo_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskTodo',
        ),
    ]
